# A simple action usage
name: Build Kernel

on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/burkvt/android_kernel_xiaomi_sdm660
          kernel-dir: kernel
          kernel-branch: "lineage-21-4.19"
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          other-gcc64-url: https://github.com/crdroidandroid/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3
          other-gcc64-branch: "15.0"
          aosp-clang: true
          other-clang-url: https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone
          other-clang-branch: 17
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
          extra-cmd: CC=gcc
          lxc: true
          lxc-patch: true
